# Generated by Django 5.1.3 on 2024-12-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_password_users_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='creator',
            new_name='user',
        ),
    ]
