# Generated by Django 5.1.3 on 2024-12-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_users_user_rename_creator_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
